repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: cargo-check
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: "v0.8.1"
    hooks:
      - id: taplo
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
