[book]
authors = ["Hampus Avekvist <hampus.avekvist@hey.com>"]
language = "en"
multilingual = false
src = "docs"
title = "TheCocktailDB API Client in Rust"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
cname = "seffra.dev"
edit-url-template = "https://github.com/seffradev/thecocktaildb-rs/edit/main/{path}"
git-repository-url = "https://github.com/seffradev/thecocktaildb-rs"
preferred-dark-theme = "ayu"
smart-punctuation = true
